def get_hive_tbl_row_count(spark, df, field_name, table_name):
    row_count_df = spark.sql(
        "select count({0}) from {1}".format(field_name, table_name)
    )
    tbl_row_count = row_count_df.head()[0]
    return tbl_row_count


create table demo_tran(subscription string,notifications array<struct<POSLog: struct<Transaction: struct<BusinessDayDate: string,BeginDateTime: string,EndDateTime: string,TillID: string,BusinessUnit: struct<UID: string,Brnd: string,Cntr: string,LocTyp: string,LocCode: string>,CurrencyCode: string,Operator: struct<ID: string>,RetailTransaction: struct<TxnStat: string,SnglOrdrMngmnt: boolean,DataQltyTrkng: boolean,Rcpt: struct<Print: boolean>,SrcPOS: struct<Type: string,Versn: string>,LineItms: array<struct<VoidFlg: boolean,EntryMthd: string,Sale: struct<ItmType: string,TxblFlg: boolean,ActlSalesUntPrice: struct<Amt: double>,Dscrptns: array<struct<Txt: string,TypeCod: string>>,XtendedAmt: struct<Amount: double>,Item: struct<ID: string,Type: string>,MerchandiseHierarchy: array<struct<Code: string,Level: string>>,Qty: struct<Qty: int>,RegSalesUnitPrice: struct<Amount: int>,RetPriceModifiers: array<struct<VoidFlag: boolean,MethodCode: string,Amount: struct<Actn: string,Amount: double>,Descriptions: array<struct<Text: string,Typecode: string>>,Prcent: struct<Prcent: double,Action: string>,PromotionID: string,Promotion: struct<ID: string,Code: string,Description: string,Type: string>,SeqNo: int>>,SuggestedPrice: struct<Amount: int>,Taxes: array<struct<TaxType: string,VoidFlag: boolean,Amount: struct<Amount: double>,Prcent: double,Rounding: struct<Amount: double>,TaxAuthority: string,TaxGroupID: string,TaxJurisdictionID: string,TaxRuleIDs: array<string>,TaxableAmt: struct<Amt: double>>>,ItemNotOnFileFlag: boolean>,ScanData: array<struct<Data: bigint>>,SeqNo1: int>>,Srvy: struct<SrvyCod: string>,Totals: array<struct<Amt: double,TotalTyp: string>>>,SequenceNumber: bigint,SourceMessageId: string,TransactionID: string,Workstation: struct<ID: string,TypeCod: string>>>>>) row format serde 'org.apache.hive.hcatalog.data.JsonSerDe';
